services:
  - type: web
    name: squ-math-backend
    env: python
    rootDir: backend
    region: oregon
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "gunicorn squ_math.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11.0
